window.TARKOV_ITEMS = window.TARKOV_GENERATED_ITEMS || [];
window.TARKOV_QUESTS = window.TARKOV_GENERATED_QUESTS || [];
window.TARKOV_HIDEOUT_UPGRADES = window.TARKOV_GENERATED_HIDEOUT_UPGRADES || [];
